version: "3.9" 
services:
  infracloud:
    image: infracloudio/csvserver:latest
    container_name: infracloud
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - $PWD/inputFile:/csvserver/inputdata
   
