version: "3.9" 
services:
  infracloud:
    image: infracloudio/csvserver:latest
    container_name: infracloud
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - $PWD/inputFile:/csvserver/inputdata
    networks:
     - infracloud-net
     
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
     - infracloud-net

networks:
  infracloud-net: 
